#  Standardize Data

In [2]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import StandardScaler
filename = 'pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
array = dataframe.values

x = array[:, 0:8]
y = array[:, 8]

scaler = StandardScaler().fit(x)
rescaledx = scaler.transform(x)

In [3]:
# summarizing transformed data
set_printoptions(precision=3)
print(rescaledx[0:5, :])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]
