## 2.1 Eigendecompositon of a Matrix

Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square matrix into a set of eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation.
<br>
A · v = λ · v <br>
This is called the eigenvector.

where:This is called the eigenvalue equation, where A is the parent square matrix that we are
decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter lambda and
represents the eigenvalue scalar.

## 2.2 Calculation of Eigendecomposition

In [2]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1,2,3],
          [4,5,6],
          [7,8,9]])

print(A)

#factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## 2.3 Confirm an Eigenvector and Eigenvalue